### ISSUE TITLE
LocalPosition, localRotation problem in PlaceArucoObject

### ISSUE THREAD

**Issue by JSGFJSG** [enormand/aruco-unity#4]
Hi, 

I'm running the tracking scene and the marker detection part goes fine. The aruco axis are shown in a right way. However, the game object has problems with translation and rotation. When I move the webcam, the marker is tracked right but the game object move is wrong. I think the problem is in the method PlaceArucoObject from the class ArucoObjectTracker. Has anybody found similar problem? How did you solve it?

Thank in advacen,

**Comment by enormand** [comment]
Hi,

The position placement offset and the rotation issues has been fixed with the latest release ([v1.2.0](https://github.com/enormand/aruco-unity/releases/tag/v1.2.0)). Can you test it and tell me if it resolved your issue? Otherwise, could you provide me a short screen capture video of your issue?

Thanks

**Comment by JSGFJSG** [comment]
Hi,

I tested it and now It is working OK. Thank very mucho for your help.

Cheers
